# Generated by Django 3.2.15 on 2022-08-26 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('ma', 'مرد'), ('fe', 'زن')], max_length=2, verbose_name='جنسیت')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=20, null=True, unique=True)),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('image', models.ImageField(default=None, upload_to='images')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان اجاد')),
                ('status', models.CharField(choices=[('p', 'انتشار'), ('d', 'پیش نویس'), ('l', 'درحال برسی'), ('b', 'برگشت داده شده')], max_length=1, verbose_name='وضعیت انتشار')),
                ('gender', models.ManyToManyField(to='shop.Gender', verbose_name='جنسیت')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
        ),
    ]
