# Generated by Django 3.2.15 on 2022-08-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='shop.Category', verbose_name='دسته بندی'),
        ),
    ]
