# Generated by Django 3.2.15 on 2022-08-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='عنوان')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت انتشار')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='condition',
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.ManyToManyField(to='shop.Condition', verbose_name='حالت'),
        ),
    ]
